---
- hosts: "{{ host }}"
  gather_facts: false
  tasks:
  - name: Create Datacenter
    vmware_datacenter:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ datacenter_name }}"
      validate_certs: False
      state: present
    delegate_to: localhost
  - name: Create Cluster
    vmware_cluster:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter_name: "{{ datacenter_name }}"
      cluster_name: "{{ cluster_name }}"
      validate_certs: False
      state: present
    delegate_to: localhost
