---
- vars_prompt:
    - name: "esxi_hostname"
      prompt: "Which ESX Host"
      private: no
    - name: "switch_name"
      prompt: "Name of Switch"
      private: no
  hosts: esx
  become: true
  become_user: root
  gather_facts: false
  tasks:
  - name: Add a VMware vSwitch
    vmware_vswitch:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      switch: "{{ switch_name }}"
      mtu: 1500
      validate_certs: False
      state: present
    delegate_to: localhost
