---
# create a new VM from a template
- vars_prompt:
    - name: "Host"
      prompt: "Which Host"
      private: no
    - name: "memory_mb"
      prompt: "How Much Memory"
      private: no
    - name: "vmname"
      prompt: "Name of VM"
      private: no
    - name: "size_gb"
      prompt: "Size of HD"
      private: no
    - name: "vlan"
      prompt: "Which VLAN"
      private: no
    - name: "ip"
      prompt: "IP"
      private: no
    - name: "netmask"
      prompt: "netmask"
      private: no
    - name: "gateway"
      prompt: "gateway"
      private: no
  hosts: "{{ Host }}"
  gather_facts: false
  connection: local
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost  }}"
        folder: "{{ folder }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vmname }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ size_gb }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: "{{ vlan }}"
          type: static
          ip: '{{ ip }}'
          netmask: '{{ netmask }}'
          gateway: '{{ gateway }}'
        hardware:
         memory_mb: "{{ memory_mb }}"
        wait_for_ip_address: True
        state: present
