---
- hosts: "{{ host }}"
  gather_facts: false
  tasks:
  - name: Set NTP Servers
    vmware_host_ntp:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter:password }}"
      cluster_name: "{{ cluster_name }}"
      ntp_servers:
          - "{{ ntp_servers }}"
      validate_certs: False
      state: present
    delegate_to: localhost
  - name: Start ntpd Service
    vmware_host_service_manager:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      cluster_name: "{{ cluster_name }}"
      service_name: ntpd
      service_policy: on
      state: present
      validate_certs: False
    delegate_to: localhost
