---
- hosts: windows
  gather_facts: false
  become: true
  tasks:
    - name: set startup type custom_service to delayed via powershell
      win_shell: 'Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\UsoSvc" | Select-Object -ExpandProperty DelayedAutoStart'
