---
- hosts: switches
  gather_facts: false
  vars_files:
    - /etc/ansible/group_vars/vault.yml
  tasks:
    - name: change hostname
      ios_config:
        lines:
          - description - Config by Ansible
        parents: interface GigabitEthernet1/0/48
