---
- hosts: "{{ host }}"
  gather_facts: false
  connection: local
  vars_files:
    - /etc/ansible/group_vars/vault.yml
  tasks:
  - name: Create vlan
    ios_vlan:
      vlan_id: "{{ vlan_id }}"
      name: "{{ name }}"
      state: present
    notify: "save ios"
  - name: Show vlan
    ios_command:
      commands: show vlan brief
    register: show_vlan
  - debug: var=show_vlan.stdout_lines
  handlers:
    - name: save ios
      ios_command:
        commands: "write mem"
        timeout: 40
      when: not ansible_check_mode
