---
- hosts: "{{ host }}"
  gather_facts: false
  connection: local
  vars_files:
    - /etc/ansible/group_vars/vault.yml
  tasks:
  - name: add login banner
    ios_banner:
      banner: motd
      text: "{{ text_for_motd }}"
      state: present
    notify: "save ios"
  handlers:
    - name: save ios
      ios_config:
        save_when: modified
