---
- hosts: switches
  gather_facts: false
  connection: local

  tasks:
    - name: change hostname
      ios_command:
          commands: show version
      register: version
    - name: second task
      debug:
        var: version
