---
- hosts: "{{ host }}"
  gather_facts: false
  connection: local
  vars_files:
    - /etc/ansible/group_vars/vault.yml
  tasks:
  - name: gather running config
    ios_command:
      commands:
        - show run
      timeout: 30
    register: config

  - debug: msg="{{ config.stdout_lines }}"
