---
- hosts: "{{ host }}"
  gather_facts: false
  connection: local
  tasks:
    - name: change IP
      ios_config:
        lines:
          - ip address "{{ ip address }}"
        parents: interface vlan "{{ vlan ID }}"
      notify: "save ios"
  handlers:
    - name: save ios
      ios_command:
        commands: "write mem"
        timeout: 40
      when: not ansible_check_mode
